mongoose=require('mongoose');
const Schema=mongoose.Schema;
const UserSchema=new Schema({
    username:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
    },
    password:{
        type:String,
        required:true
    },
    privacy:{
        type:String,
        enum:['public','private','friendsOnly'],
        default:'public'
    },
    role:{
        type:String,
        enum:['user','admin'],
        default:'user'
    },
    friends:[{
        type:Schema.Types.ObjectId,
        ref:'User'
    }]
});
module.exports=mongoose.model('User',UserSchema);